let input1t = `id=1, plug=BLUE HEXAGON, leftSocket=GREEN CIRCLE, rightSocket=BLUE PENTAGON, data=?
id=2, plug=GREEN CIRCLE, leftSocket=BLUE HEXAGON, rightSocket=BLUE CIRCLE, data=?
id=3, plug=BLUE PENTAGON, leftSocket=BLUE CIRCLE, rightSocket=BLUE CIRCLE, data=?
id=4, plug=BLUE CIRCLE, leftSocket=RED HEXAGON, rightSocket=BLUE HEXAGON, data=?
id=5, plug=RED HEXAGON, leftSocket=GREEN CIRCLE, rightSocket=RED HEXAGON, data=?`

let input2t = `id=1, plug=RED TRIANGLE, leftSocket=RED TRIANGLE, rightSocket=RED TRIANGLE, data=?
id=2, plug=GREEN TRIANGLE, leftSocket=BLUE CIRCLE, rightSocket=GREEN CIRCLE, data=?
id=3, plug=BLUE PENTAGON, leftSocket=BLUE CIRCLE, rightSocket=GREEN CIRCLE, data=?
id=4, plug=RED TRIANGLE, leftSocket=BLUE PENTAGON, rightSocket=GREEN PENTAGON, data=?
id=5, plug=RED PENTAGON, leftSocket=GREEN CIRCLE, rightSocket=GREEN CIRCLE, data=?`

let input1 = `id=1, plug=WHITE HEXAGON, leftSocket=WHITE TRIANGLE, rightSocket=BLACK SQUARE, data=---------------------
id=2, plug=BLACK SQUARE, leftSocket=BLACK PENTAGON, rightSocket=GREEN PENTAGON, data=------------3--------
id=3, plug=BLACK PENTAGON, leftSocket=BLACK SQUARE, rightSocket=GREEN HEXAGON, data=-----------3---------
id=4, plug=GREEN HEXAGON, leftSocket=WHITE TRIANGLE, rightSocket=BLUE TRIANGLE, data=--------3------------
id=5, plug=BLUE TRIANGLE, leftSocket=WHITE CIRCLE, rightSocket=GREEN HEXAGON, data=-------------3-------
id=6, plug=WHITE TRIANGLE, leftSocket=WHITE TRIANGLE, rightSocket=BLUE PENTAGON, data=--------3------------
id=7, plug=BLUE PENTAGON, leftSocket=WHITE CIRCLE, rightSocket=BLUE CIRCLE, data=-----------3---------
id=8, plug=WHITE CIRCLE, leftSocket=GREEN SQUARE, rightSocket=WHITE SQUARE, data=------------3--------
id=9, plug=WHITE TRIANGLE, leftSocket=BLUE HEXAGON, rightSocket=WHITE PENTAGON, data=-----------3---------
id=10, plug=WHITE CIRCLE, leftSocket=WHITE PENTAGON, rightSocket=BLACK CIRCLE, data=-------------3-------
id=11, plug=BLUE CIRCLE, leftSocket=BLACK HEXAGON, rightSocket=BLUE CIRCLE, data=---------------------
id=12, plug=GREEN HEXAGON, leftSocket=RED SQUARE, rightSocket=BLUE CIRCLE, data=------------3--------
id=13, plug=WHITE PENTAGON, leftSocket=WHITE HEXAGON, rightSocket=BLUE SQUARE, data=---------3-----------
id=14, plug=GREEN PENTAGON, leftSocket=RED HEXAGON, rightSocket=WHITE TRIANGLE, data=-----------3---------
id=15, plug=WHITE PENTAGON, leftSocket=BLUE TRIANGLE, rightSocket=BLUE TRIANGLE, data=---------------------
id=16, plug=BLACK SQUARE, leftSocket=WHITE PENTAGON, rightSocket=GREEN SQUARE, data=--------3------------
id=17, plug=WHITE TRIANGLE, leftSocket=WHITE HEXAGON, rightSocket=WHITE CIRCLE, data=-----------3---------
id=18, plug=WHITE HEXAGON, leftSocket=GREEN HEXAGON, rightSocket=BLACK HEXAGON, data=-----------3---------
id=19, plug=GREEN SQUARE, leftSocket=WHITE PENTAGON, rightSocket=BLUE TRIANGLE, data=-------------3-------
id=20, plug=BLUE TRIANGLE, leftSocket=BLUE TRIANGLE, rightSocket=WHITE PENTAGON, data=------------3--------
id=21, plug=WHITE CIRCLE, leftSocket=BLACK CIRCLE, rightSocket=GREEN SQUARE, data=---------3-----------
id=22, plug=BLACK HEXAGON, leftSocket=BLUE SQUARE, rightSocket=RED PENTAGON, data=--------3------------
id=23, plug=BLACK CIRCLE, leftSocket=GREEN CIRCLE, rightSocket=BLACK CIRCLE, data=--------3------------
id=24, plug=BLUE SQUARE, leftSocket=RED SQUARE, rightSocket=WHITE CIRCLE, data=-----------3---------
id=25, plug=BLACK CIRCLE, leftSocket=BLUE SQUARE, rightSocket=GREEN PENTAGON, data=---------3-----------
id=26, plug=WHITE PENTAGON, leftSocket=RED SQUARE, rightSocket=RED PENTAGON, data=---------------------
id=27, plug=RED PENTAGON, leftSocket=GREEN CIRCLE, rightSocket=GREEN SQUARE, data=---------3-----------
id=28, plug=WHITE HEXAGON, leftSocket=BLACK SQUARE, rightSocket=BLUE TRIANGLE, data=-----------3---------
id=29, plug=BLUE TRIANGLE, leftSocket=RED CIRCLE, rightSocket=BLUE CIRCLE, data=-------------3-------`

let input2 = `id=1, plug=BLACK OCTAGON, leftSocket=MAGENTA SQUARE, rightSocket=RED PENTAGON, data=---33-----22---------
id=2, plug=RED OCTAGON, leftSocket=CYAN SQUARE, rightSocket=YELLOW SQUARE, data=--------------------1
id=3, plug=YELLOW TRIANGLE, leftSocket=RED PENTAGON, rightSocket=BLACK TRIANGLE, data=---------------------
id=4, plug=RED DIAMOND, leftSocket=WHITE TRIANGLE, rightSocket=WHITE HEXAGON, data=1--------------------
id=5, plug=WHITE OCTAGON, leftSocket=WHITE CIRCLE, rightSocket=YELLOW OCTAGON, data=---------------------
id=6, plug=WHITE DIAMOND, leftSocket=RED PENTAGON, rightSocket=CYAN DIAMOND, data=1--33-----22---------
id=7, plug=BLACK CIRCLE, leftSocket=BLUE DIAMOND, rightSocket=BLUE DIAMOND, data=-----3-3----2-2-----1
id=8, plug=YELLOW OCTAGON, leftSocket=BLUE PENTAGON, rightSocket=WHITE TRIANGLE, data=------3-3----2-2----1
id=9, plug=CYAN OCTAGON, leftSocket=YELLOW DIAMOND, rightSocket=BLUE STAR, data=---------------------
id=10, plug=MAGENTA TRIANGLE, leftSocket=YELLOW DIAMOND, rightSocket=CYAN TRIANGLE, data=--------------------1
id=11, plug=WHITE HEXAGON, leftSocket=YELLOW PENTAGON, rightSocket=RED DIAMOND, data=---------------------
id=12, plug=RED STAR, leftSocket=WHITE CIRCLE, rightSocket=MAGENTA SQUARE, data=---33-----22--------1
id=13, plug=YELLOW OCTAGON, leftSocket=RED OCTAGON, rightSocket=CYAN CIRCLE, data=--------------------1
id=14, plug=BLUE DIAMOND, leftSocket=YELLOW SQUARE, rightSocket=BLUE PENTAGON, data=1--------------------
id=15, plug=BLUE OCTAGON, leftSocket=MAGENTA STAR, rightSocket=YELLOW CIRCLE, data=---------------------
id=16, plug=CYAN PENTAGON, leftSocket=GREEN DIAMOND, rightSocket=YELLOW TRIANGLE, data=---------------------
id=17, plug=GREEN SQUARE, leftSocket=WHITE HEXAGON, rightSocket=BLACK DIAMOND, data=1---3-3----2-2-------
id=18, plug=WHITE DIAMOND, leftSocket=RED HEXAGON, rightSocket=BLACK SQUARE, data=--------------------1
id=19, plug=BLACK STAR, leftSocket=CYAN OCTAGON, rightSocket=BLUE HEXAGON, data=-----3-3----2-2-----1
id=20, plug=CYAN SQUARE, leftSocket=CYAN SQUARE, rightSocket=GREEN DIAMOND, data=-----3------2-------1
id=21, plug=WHITE CIRCLE, leftSocket=CYAN CIRCLE, rightSocket=MAGENTA CIRCLE, data=1--------------------
id=22, plug=MAGENTA TRIANGLE, leftSocket=BLUE DIAMOND, rightSocket=YELLOW PENTAGON, data=------3-3----2-2-----
id=23, plug=CYAN HEXAGON, leftSocket=WHITE SQUARE, rightSocket=BLACK STAR, data=1------3-3----2-2----
id=24, plug=RED DIAMOND, leftSocket=CYAN SQUARE, rightSocket=BLUE SQUARE, data=1------3------2------
id=25, plug=YELLOW STAR, leftSocket=CYAN OCTAGON, rightSocket=BLACK DIAMOND, data=-------3-3----2-2----
id=26, plug=WHITE PENTAGON, leftSocket=YELLOW OCTAGON, rightSocket=CYAN HEXAGON, data=--------------------1
id=27, plug=YELLOW CIRCLE, leftSocket=YELLOW DIAMOND, rightSocket=GREEN DIAMOND, data=------3-3----2-2-----
id=28, plug=BLUE PENTAGON, leftSocket=RED DIAMOND, rightSocket=GREEN STAR, data=-----3------2--------
id=29, plug=GREEN DIAMOND, leftSocket=BLUE OCTAGON, rightSocket=GREEN SQUARE, data=1--------------------
id=30, plug=BLUE HEXAGON, leftSocket=GREEN SQUARE, rightSocket=YELLOW TRIANGLE, data=-----3------2-------1
id=31, plug=BLACK CIRCLE, leftSocket=WHITE SQUARE, rightSocket=BLUE CIRCLE, data=--------------------1
id=32, plug=BLACK CIRCLE, leftSocket=MAGENTA SQUARE, rightSocket=MAGENTA TRIANGLE, data=1--------------------
id=33, plug=YELLOW TRIANGLE, leftSocket=MAGENTA SQUARE, rightSocket=MAGENTA DIAMOND, data=---------3-3----2-2-1
id=34, plug=YELLOW TRIANGLE, leftSocket=BLUE STAR, rightSocket=WHITE CIRCLE, data=----3------2--------1
id=35, plug=BLUE TRIANGLE, leftSocket=MAGENTA OCTAGON, rightSocket=GREEN DIAMOND, data=---------------------
id=36, plug=GREEN SQUARE, leftSocket=YELLOW PENTAGON, rightSocket=BLUE SQUARE, data=1-----3-3----2-2-----
id=37, plug=BLUE CIRCLE, leftSocket=MAGENTA TRIANGLE, rightSocket=BLUE STAR, data=----3------2--------1
id=38, plug=GREEN DIAMOND, leftSocket=RED SQUARE, rightSocket=GREEN TRIANGLE, data=---------------------
id=39, plug=MAGENTA CIRCLE, leftSocket=BLUE SQUARE, rightSocket=YELLOW DIAMOND, data=---------------------
id=40, plug=MAGENTA HEXAGON, leftSocket=CYAN PENTAGON, rightSocket=CYAN HEXAGON, data=1------3------2------
id=41, plug=MAGENTA HEXAGON, leftSocket=BLACK DIAMOND, rightSocket=RED OCTAGON, data=-----3------2--------
id=42, plug=WHITE HEXAGON, leftSocket=GREEN PENTAGON, rightSocket=YELLOW SQUARE, data=--------------------1
id=43, plug=CYAN SQUARE, leftSocket=CYAN TRIANGLE, rightSocket=CYAN OCTAGON, data=1--------------------
id=44, plug=MAGENTA CIRCLE, leftSocket=BLUE CIRCLE, rightSocket=YELLOW SQUARE, data=---------------------
id=45, plug=YELLOW PENTAGON, leftSocket=CYAN HEXAGON, rightSocket=GREEN HEXAGON, data=----3------2--------1
id=46, plug=BLUE TRIANGLE, leftSocket=WHITE STAR, rightSocket=BLUE PENTAGON, data=---------------------
id=47, plug=GREEN TRIANGLE, leftSocket=WHITE STAR, rightSocket=YELLOW OCTAGON, data=--------------------1
id=48, plug=WHITE CIRCLE, leftSocket=GREEN OCTAGON, rightSocket=BLACK SQUARE, data=------3--3---2--2----
id=49, plug=YELLOW PENTAGON, leftSocket=WHITE DIAMOND, rightSocket=BLUE SQUARE, data=--------------------1
id=50, plug=BLACK OCTAGON, leftSocket=GREEN DIAMOND, rightSocket=YELLOW HEXAGON, data=---------------------
id=51, plug=CYAN DIAMOND, leftSocket=YELLOW PENTAGON, rightSocket=RED TRIANGLE, data=-1-----------------1-
id=52, plug=MAGENTA STAR, leftSocket=GREEN SQUARE, rightSocket=MAGENTA DIAMOND, data=------3-3----2-2-----
id=53, plug=YELLOW HEXAGON, leftSocket=WHITE OCTAGON, rightSocket=WHITE OCTAGON, data=--------------------1
id=54, plug=CYAN HEXAGON, leftSocket=WHITE SQUARE, rightSocket=YELLOW HEXAGON, data=1--------------------
id=55, plug=MAGENTA CIRCLE, leftSocket=BLUE OCTAGON, rightSocket=BLUE SQUARE, data=--------------------1
id=56, plug=GREEN CIRCLE, leftSocket=BLACK OCTAGON, rightSocket=YELLOW STAR, data=-----3------2-------1
id=57, plug=YELLOW HEXAGON, leftSocket=WHITE CIRCLE, rightSocket=BLACK DIAMOND, data=------3--3---2--2---1
id=58, plug=RED TRIANGLE, leftSocket=YELLOW CIRCLE, rightSocket=BLACK STAR, data=---------------------
id=59, plug=YELLOW SQUARE, leftSocket=GREEN HEXAGON, rightSocket=YELLOW DIAMOND, data=-------------------1-
id=60, plug=BLUE CIRCLE, leftSocket=GREEN SQUARE, rightSocket=WHITE PENTAGON, data=-----3------2--------
id=61, plug=CYAN HEXAGON, leftSocket=BLACK SQUARE, rightSocket=BLUE HEXAGON, data=1-------------------1
id=62, plug=YELLOW DIAMOND, leftSocket=BLUE SQUARE, rightSocket=YELLOW STAR, data=1-------------------1
id=63, plug=WHITE HEXAGON, leftSocket=GREEN PENTAGON, rightSocket=BLACK PENTAGON, data=---------------------
id=64, plug=YELLOW PENTAGON, leftSocket=RED STAR, rightSocket=BLUE OCTAGON, data=1--33-----22---------
id=65, plug=RED CIRCLE, leftSocket=CYAN DIAMOND, rightSocket=BLUE PENTAGON, data=1--------------------
id=66, plug=BLUE SQUARE, leftSocket=YELLOW STAR, rightSocket=MAGENTA STAR, data=--------------------1
id=67, plug=BLUE TRIANGLE, leftSocket=RED DIAMOND, rightSocket=BLUE STAR, data=------3-3----2-2----1
id=68, plug=GREEN PENTAGON, leftSocket=RED STAR, rightSocket=BLUE OCTAGON, data=-----3-3----2-2-----1
id=69, plug=GREEN TRIANGLE, leftSocket=CYAN TRIANGLE, rightSocket=BLUE SQUARE, data=1------3------2------
id=70, plug=RED CIRCLE, leftSocket=YELLOW PENTAGON, rightSocket=CYAN DIAMOND, data=---------------------
id=71, plug=WHITE SQUARE, leftSocket=WHITE SQUARE, rightSocket=CYAN SQUARE, data=1-------------------1
id=72, plug=BLACK STAR, leftSocket=MAGENTA SQUARE, rightSocket=BLACK TRIANGLE, data=---------------------
id=73, plug=BLUE HEXAGON, leftSocket=YELLOW CIRCLE, rightSocket=WHITE TRIANGLE, data=---------------------
id=74, plug=CYAN HEXAGON, leftSocket=CYAN STAR, rightSocket=YELLOW PENTAGON, data=---33-----22---------
id=75, plug=CYAN STAR, leftSocket=RED CIRCLE, rightSocket=WHITE STAR, data=------3-3----2-2-----
id=76, plug=WHITE PENTAGON, leftSocket=WHITE OCTAGON, rightSocket=YELLOW DIAMOND, data=---------------------
id=77, plug=YELLOW OCTAGON, leftSocket=GREEN CIRCLE, rightSocket=MAGENTA DIAMOND, data=-----3------2-------1
id=78, plug=WHITE HEXAGON, leftSocket=GREEN STAR, rightSocket=CYAN SQUARE, data=1--------------------
id=79, plug=BLUE TRIANGLE, leftSocket=CYAN PENTAGON, rightSocket=RED OCTAGON, data=---33-----22--------1
id=80, plug=MAGENTA HEXAGON, leftSocket=YELLOW OCTAGON, rightSocket=MAGENTA TRIANGLE, data=1---3-3----2-2-------
id=81, plug=YELLOW DIAMOND, leftSocket=GREEN DIAMOND, rightSocket=WHITE OCTAGON, data=-----3------2--------
id=82, plug=WHITE OCTAGON, leftSocket=MAGENTA CIRCLE, rightSocket=BLACK CIRCLE, data=--------------------1
id=83, plug=MAGENTA STAR, leftSocket=WHITE PENTAGON, rightSocket=CYAN SQUARE, data=1--------------------
id=84, plug=GREEN HEXAGON, leftSocket=BLACK STAR, rightSocket=MAGENTA PENTAGON, data=----3------2--------1
id=85, plug=YELLOW HEXAGON, leftSocket=RED STAR, rightSocket=BLUE CIRCLE, data=--------------------1
id=86, plug=CYAN HEXAGON, leftSocket=CYAN PENTAGON, rightSocket=CYAN TRIANGLE, data=--------------------1
id=87, plug=CYAN OCTAGON, leftSocket=RED TRIANGLE, rightSocket=GREEN TRIANGLE, data=------3-3----2-2-----
id=88, plug=WHITE STAR, leftSocket=YELLOW HEXAGON, rightSocket=CYAN HEXAGON, data=---------------------
id=89, plug=YELLOW HEXAGON, leftSocket=CYAN PENTAGON, rightSocket=BLUE DIAMOND, data=---------------------
id=90, plug=WHITE OCTAGON, leftSocket=GREEN DIAMOND, rightSocket=MAGENTA OCTAGON, data=-----3-3----2-2-----1
id=91, plug=WHITE OCTAGON, leftSocket=WHITE STAR, rightSocket=WHITE HEXAGON, data=---------------------
id=92, plug=YELLOW HEXAGON, leftSocket=WHITE CIRCLE, rightSocket=BLUE OCTAGON, data=1--------------------
id=93, plug=GREEN TRIANGLE, leftSocket=GREEN CIRCLE, rightSocket=BLACK DIAMOND, data=1------3------2------
id=94, plug=MAGENTA DIAMOND, leftSocket=GREEN SQUARE, rightSocket=BLUE HEXAGON, data=--------------------1
id=95, plug=BLUE STAR, leftSocket=BLACK SQUARE, rightSocket=MAGENTA PENTAGON, data=-----3-3----2-2------
id=96, plug=BLUE DIAMOND, leftSocket=WHITE DIAMOND, rightSocket=BLUE SQUARE, data=---------------------
id=97, plug=BLACK TRIANGLE, leftSocket=CYAN TRIANGLE, rightSocket=GREEN CIRCLE, data=1----3-3----2-2------
id=98, plug=CYAN OCTAGON, leftSocket=CYAN DIAMOND, rightSocket=MAGENTA HEXAGON, data=-----3------2--------
id=99, plug=YELLOW SQUARE, leftSocket=GREEN SQUARE, rightSocket=WHITE PENTAGON, data=------3-3----2-2-----
id=100, plug=BLUE PENTAGON, leftSocket=BLACK SQUARE, rightSocket=MAGENTA CIRCLE, data=--------------------1
id=101, plug=WHITE PENTAGON, leftSocket=MAGENTA STAR, rightSocket=BLUE SQUARE, data=--------------------1
id=102, plug=YELLOW DIAMOND, leftSocket=WHITE TRIANGLE, rightSocket=BLACK HEXAGON, data=1------3------2------
id=103, plug=MAGENTA SQUARE, leftSocket=MAGENTA CIRCLE, rightSocket=CYAN HEXAGON, data=------3-3----2-2----1
id=104, plug=WHITE DIAMOND, leftSocket=WHITE STAR, rightSocket=YELLOW SQUARE, data=-----3------2-------1
id=105, plug=WHITE PENTAGON, leftSocket=GREEN OCTAGON, rightSocket=MAGENTA OCTAGON, data=---------------------
id=106, plug=MAGENTA CIRCLE, leftSocket=CYAN STAR, rightSocket=CYAN SQUARE, data=----3------2--------1
id=107, plug=MAGENTA OCTAGON, leftSocket=BLUE DIAMOND, rightSocket=YELLOW OCTAGON, data=--------------------1
id=108, plug=MAGENTA CIRCLE, leftSocket=CYAN DIAMOND, rightSocket=CYAN CIRCLE, data=----3------2--------1
id=109, plug=BLACK OCTAGON, leftSocket=CYAN SQUARE, rightSocket=YELLOW STAR, data=---------------------
id=110, plug=GREEN SQUARE, leftSocket=BLACK HEXAGON, rightSocket=WHITE PENTAGON, data=--------------------1
id=111, plug=GREEN TRIANGLE, leftSocket=BLACK STAR, rightSocket=MAGENTA CIRCLE, data=1--------------------
id=112, plug=BLUE HEXAGON, leftSocket=WHITE STAR, rightSocket=CYAN CIRCLE, data=------3--3---2--2----
id=113, plug=WHITE CIRCLE, leftSocket=BLUE CIRCLE, rightSocket=RED PENTAGON, data=1------3------2------
id=114, plug=WHITE HEXAGON, leftSocket=WHITE OCTAGON, rightSocket=YELLOW OCTAGON, data=1-----3-3----2-2-----
id=115, plug=WHITE STAR, leftSocket=GREEN TRIANGLE, rightSocket=GREEN HEXAGON, data=1--------------------
id=116, plug=MAGENTA STAR, leftSocket=YELLOW SQUARE, rightSocket=CYAN DIAMOND, data=1--------------------
id=117, plug=BLUE SQUARE, leftSocket=BLACK TRIANGLE, rightSocket=BLACK STAR, data=-----3------2-------1
id=118, plug=YELLOW PENTAGON, leftSocket=RED DIAMOND, rightSocket=YELLOW OCTAGON, data=---------------------
id=119, plug=CYAN DIAMOND, leftSocket=RED HEXAGON, rightSocket=RED STAR, data=------3--3---2--2---1
id=120, plug=MAGENTA OCTAGON, leftSocket=CYAN OCTAGON, rightSocket=YELLOW DIAMOND, data=1--------------------
id=121, plug=WHITE CIRCLE, leftSocket=MAGENTA HEXAGON, rightSocket=CYAN HEXAGON, data=--------------------1
id=122, plug=RED CIRCLE, leftSocket=WHITE HEXAGON, rightSocket=BLACK HEXAGON, data=-----3------2--------
id=123, plug=RED HEXAGON, leftSocket=CYAN SQUARE, rightSocket=BLUE CIRCLE, data=---------------------`

let input3t = `id=1, plug=RED TRIANGLE, leftSocket=RED TRIANGLE, rightSocket=RED TRIANGLE, data=?
id=2, plug=GREEN TRIANGLE, leftSocket=BLUE CIRCLE, rightSocket=GREEN CIRCLE, data=?
id=3, plug=BLUE PENTAGON, leftSocket=BLUE CIRCLE, rightSocket=GREEN CIRCLE, data=?
id=4, plug=RED TRIANGLE, leftSocket=BLUE PENTAGON, rightSocket=GREEN PENTAGON, data=?
id=5, plug=RED PENTAGON, leftSocket=GREEN CIRCLE, rightSocket=GREEN CIRCLE, data=?`

let input3t2 = `id=1, plug=RED TRIANGLE, leftSocket=BLUE TRIANGLE, rightSocket=GREEN TRIANGLE, data=?
id=2, plug=GREEN TRIANGLE, leftSocket=BLUE CIRCLE, rightSocket=GREEN CIRCLE, data=?
id=3, plug=BLUE PENTAGON, leftSocket=BLUE CIRCLE, rightSocket=GREEN CIRCLE, data=?
id=4, plug=RED TRIANGLE, leftSocket=BLUE PENTAGON, rightSocket=GREEN PENTAGON, data=?
id=5, plug=BLUE TRIANGLE, leftSocket=GREEN CIRCLE, rightSocket=RED CIRCLE, data=?
id=6, plug=BLUE TRIANGLE, leftSocket=GREEN CIRCLE, rightSocket=RED CIRCLE, data=?`

let input3 = `id=1, plug=WHITE DIAMOND, leftSocket=YELLOW TRIANGLE, rightSocket=BLUE HEXAGON, data=-------------------3-
id=2, plug=YELLOW HEXAGON, leftSocket=BLUE DIAMOND, rightSocket=BLUE CIRCLE, data=-----------------2---
id=3, plug=BLUE HEXAGON, leftSocket=GREEN OCTAGON, rightSocket=BLACK HEXAGON, data=-------1------3-----1
id=4, plug=BLACK HEXAGON, leftSocket=YELLOW OCTAGON, rightSocket=BLACK DIAMOND, data=---------------------
id=5, plug=BLUE HEXAGON, leftSocket=RED STAR, rightSocket=MAGENTA HEXAGON, data=-11111------33333----
id=6, plug=BLUE CIRCLE, leftSocket=WHITE CIRCLE, rightSocket=MAGENTA DIAMOND, data=---------------------
id=7, plug=BLACK OCTAGON, leftSocket=MAGENTA TRIANGLE, rightSocket=BLACK SQUARE, data=------1------3-------
id=8, plug=WHITE HEXAGON, leftSocket=YELLOW HEXAGON, rightSocket=MAGENTA DIAMOND, data=------1------3-------
id=9, plug=YELLOW STAR, leftSocket=WHITE HEXAGON, rightSocket=MAGENTA DIAMOND, data=-----1------3--------
id=10, plug=RED OCTAGON, leftSocket=BLUE HEXAGON, rightSocket=GREEN DIAMOND, data=-------1------3------
id=11, plug=MAGENTA HEXAGON, leftSocket=CYAN PENTAGON, rightSocket=BLUE OCTAGON, data=----1------3---------
id=12, plug=WHITE OCTAGON, leftSocket=WHITE HEXAGON, rightSocket=GREEN TRIANGLE, data=---------------------
id=13, plug=GREEN PENTAGON, leftSocket=WHITE HEXAGON, rightSocket=WHITE TRIANGLE, data=---------------------
id=14, plug=MAGENTA TRIANGLE, leftSocket=GREEN DIAMOND, rightSocket=MAGENTA HEXAGON, data=------1------3-------
id=15, plug=GREEN CIRCLE, leftSocket=YELLOW CIRCLE, rightSocket=WHITE OCTAGON, data=---1------3--------1-
id=16, plug=BLUE CIRCLE, leftSocket=YELLOW PENTAGON, rightSocket=MAGENTA OCTAGON, data=-1-1----3-3-----3---1
id=17, plug=WHITE STAR, leftSocket=CYAN TRIANGLE, rightSocket=BLUE CIRCLE, data=----1------3--------1
id=18, plug=BLUE SQUARE, leftSocket=MAGENTA TRIANGLE, rightSocket=MAGENTA STAR, data=----1------3---------
id=19, plug=MAGENTA SQUARE, leftSocket=MAGENTA TRIANGLE, rightSocket=BLUE OCTAGON, data=-----------------2---
id=20, plug=BLUE STAR, leftSocket=BLUE HEXAGON, rightSocket=RED SQUARE, data=---1------3-------2--
id=21, plug=MAGENTA PENTAGON, leftSocket=YELLOW OCTAGON, rightSocket=GREEN OCTAGON, data=---1------3----------
id=22, plug=YELLOW DIAMOND, leftSocket=MAGENTA STAR, rightSocket=RED HEXAGON, data=---1------3-------2--
id=23, plug=MAGENTA OCTAGON, leftSocket=RED SQUARE, rightSocket=BLACK TRIANGLE, data=-1------3------------
id=24, plug=BLUE SQUARE, leftSocket=GREEN SQUARE, rightSocket=GREEN OCTAGON, data=-1------3------------
id=25, plug=BLUE SQUARE, leftSocket=RED STAR, rightSocket=WHITE DIAMOND, data=----1------3--------1
id=26, plug=MAGENTA STAR, leftSocket=WHITE PENTAGON, rightSocket=WHITE PENTAGON, data=-1-1----3-3-----3---1
id=27, plug=GREEN PENTAGON, leftSocket=BLACK CIRCLE, rightSocket=GREEN HEXAGON, data=-1------3------------
id=28, plug=GREEN HEXAGON, leftSocket=YELLOW OCTAGON, rightSocket=RED PENTAGON, data=-1------3------------
id=29, plug=MAGENTA CIRCLE, leftSocket=BLUE HEXAGON, rightSocket=RED OCTAGON, data=----1------3---------
id=30, plug=MAGENTA STAR, leftSocket=YELLOW OCTAGON, rightSocket=WHITE STAR, data=---1------3--------1-
id=31, plug=MAGENTA DIAMOND, leftSocket=MAGENTA OCTAGON, rightSocket=RED HEXAGON, data=----1------3---------
id=32, plug=WHITE CIRCLE, leftSocket=MAGENTA OCTAGON, rightSocket=WHITE SQUARE, data=-----------------2---
id=33, plug=YELLOW OCTAGON, leftSocket=RED CIRCLE, rightSocket=MAGENTA DIAMOND, data=---1------3----------
id=34, plug=GREEN HEXAGON, leftSocket=YELLOW PENTAGON, rightSocket=BLUE SQUARE, data=----1------3--------1
id=35, plug=RED CIRCLE, leftSocket=BLACK OCTAGON, rightSocket=WHITE TRIANGLE, data=---1------3---------1
id=36, plug=RED OCTAGON, leftSocket=BLUE TRIANGLE, rightSocket=BLACK HEXAGON, data=-------1------3------
id=37, plug=WHITE OCTAGON, leftSocket=GREEN OCTAGON, rightSocket=CYAN STAR, data=---------------------
id=38, plug=WHITE HEXAGON, leftSocket=YELLOW DIAMOND, rightSocket=BLACK OCTAGON, data=----1------3---------
id=39, plug=BLUE DIAMOND, leftSocket=CYAN DIAMOND, rightSocket=MAGENTA SQUARE, data=------1------3-------
id=40, plug=GREEN TRIANGLE, leftSocket=GREEN TRIANGLE, rightSocket=WHITE OCTAGON, data=-----1------3-------1
id=41, plug=GREEN HEXAGON, leftSocket=GREEN OCTAGON, rightSocket=GREEN HEXAGON, data=----1------3-------1-
id=42, plug=BLACK TRIANGLE, leftSocket=YELLOW HEXAGON, rightSocket=BLUE HEXAGON, data=---------------------
id=43, plug=YELLOW STAR, leftSocket=BLACK DIAMOND, rightSocket=WHITE SQUARE, data=---------------------
id=44, plug=WHITE SQUARE, leftSocket=CYAN PENTAGON, rightSocket=CYAN CIRCLE, data=--1-1----3-3----3---1
id=45, plug=CYAN PENTAGON, leftSocket=GREEN PENTAGON, rightSocket=CYAN OCTAGON, data=--1------3-----------
id=46, plug=WHITE DIAMOND, leftSocket=WHITE STAR, rightSocket=WHITE CIRCLE, data=-----1------3--------
id=47, plug=BLACK DIAMOND, leftSocket=CYAN CIRCLE, rightSocket=WHITE PENTAGON, data=-------1------3------
id=48, plug=MAGENTA PENTAGON, leftSocket=MAGENTA SQUARE, rightSocket=WHITE DIAMOND, data=----1-1----3-3------1
id=49, plug=GREEN PENTAGON, leftSocket=BLUE SQUARE, rightSocket=RED OCTAGON, data=1-1----3-3----------1
id=50, plug=WHITE PENTAGON, leftSocket=CYAN OCTAGON, rightSocket=BLACK DIAMOND, data=---1-1----3-3-------1
id=51, plug=CYAN PENTAGON, leftSocket=GREEN PENTAGON, rightSocket=BLUE STAR, data=--1------3-----------
id=52, plug=GREEN PENTAGON, leftSocket=MAGENTA HEXAGON, rightSocket=BLACK SQUARE, data=----1------3---------
id=53, plug=CYAN CIRCLE, leftSocket=CYAN STAR, rightSocket=BLACK DIAMOND, data=---------------------
id=54, plug=BLACK CIRCLE, leftSocket=BLUE STAR, rightSocket=CYAN OCTAGON, data=---------------------
id=55, plug=BLACK CIRCLE, leftSocket=GREEN OCTAGON, rightSocket=BLACK OCTAGON, data=---------------------
id=56, plug=MAGENTA PENTAGON, leftSocket=WHITE STAR, rightSocket=BLUE TRIANGLE, data=---------------------
id=57, plug=GREEN DIAMOND, leftSocket=RED HEXAGON, rightSocket=YELLOW HEXAGON, data=------1------3-------
id=58, plug=WHITE CIRCLE, leftSocket=MAGENTA HEXAGON, rightSocket=RED DIAMOND, data=---1-1----3-3-------1
id=59, plug=CYAN OCTAGON, leftSocket=YELLOW TRIANGLE, rightSocket=BLACK PENTAGON, data=----1------3-------1-
id=60, plug=MAGENTA STAR, leftSocket=MAGENTA DIAMOND, rightSocket=RED TRIANGLE, data=---------------------
id=61, plug=YELLOW CIRCLE, leftSocket=MAGENTA HEXAGON, rightSocket=BLUE HEXAGON, data=----1------3------2--
id=62, plug=BLACK STAR, leftSocket=WHITE OCTAGON, rightSocket=CYAN STAR, data=-----1------3-------1
id=63, plug=GREEN SQUARE, leftSocket=YELLOW OCTAGON, rightSocket=RED HEXAGON, data=---1------3----------
id=64, plug=GREEN PENTAGON, leftSocket=RED STAR, rightSocket=GREEN SQUARE, data=----1------3------2--
id=65, plug=MAGENTA TRIANGLE, leftSocket=RED TRIANGLE, rightSocket=WHITE PENTAGON, data=--1-1----3-3----3---1
id=66, plug=RED TRIANGLE, leftSocket=YELLOW TRIANGLE, rightSocket=BLUE TRIANGLE, data=-----1------3-------1
id=67, plug=RED SQUARE, leftSocket=BLACK CIRCLE, rightSocket=WHITE DIAMOND, data=--1------3-----------
id=68, plug=RED STAR, leftSocket=GREEN SQUARE, rightSocket=BLACK STAR, data=-----1------3--------
id=69, plug=RED OCTAGON, leftSocket=RED HEXAGON, rightSocket=CYAN DIAMOND, data=-----1------3--------
id=70, plug=YELLOW OCTAGON, leftSocket=BLUE CIRCLE, rightSocket=WHITE CIRCLE, data=--1-1----3-3--------1
id=71, plug=YELLOW STAR, leftSocket=RED DIAMOND, rightSocket=GREEN TRIANGLE, data=----1------3---------
id=72, plug=YELLOW HEXAGON, leftSocket=WHITE CIRCLE, rightSocket=GREEN TRIANGLE, data=----1------3---------
id=73, plug=YELLOW STAR, leftSocket=WHITE HEXAGON, rightSocket=MAGENTA OCTAGON, data=--1------3-----------
id=74, plug=YELLOW PENTAGON, leftSocket=YELLOW SQUARE, rightSocket=GREEN HEXAGON, data=-----------------2---
id=75, plug=RED HEXAGON, leftSocket=BLUE OCTAGON, rightSocket=BLUE OCTAGON, data=---------------------
id=76, plug=CYAN CIRCLE, leftSocket=BLUE DIAMOND, rightSocket=BLACK STAR, data=---1------3--------1-
id=77, plug=GREEN CIRCLE, leftSocket=CYAN STAR, rightSocket=BLACK SQUARE, data=---------------------
id=78, plug=WHITE HEXAGON, leftSocket=CYAN STAR, rightSocket=RED PENTAGON, data=---------------------
id=79, plug=BLACK HEXAGON, leftSocket=BLACK CIRCLE, rightSocket=BLUE DIAMOND, data=---------------------
id=80, plug=RED CIRCLE, leftSocket=CYAN DIAMOND, rightSocket=RED SQUARE, data=----1------3---------
id=81, plug=RED CIRCLE, leftSocket=GREEN SQUARE, rightSocket=WHITE DIAMOND, data=---1-1----3-3-------1
id=82, plug=WHITE CIRCLE, leftSocket=BLUE TRIANGLE, rightSocket=CYAN STAR, data=---------------------
id=83, plug=GREEN TRIANGLE, leftSocket=WHITE PENTAGON, rightSocket=MAGENTA TRIANGLE, data=------1------3-------
id=84, plug=GREEN PENTAGON, leftSocket=CYAN TRIANGLE, rightSocket=GREEN SQUARE, data=------1------3-------
id=85, plug=CYAN CIRCLE, leftSocket=YELLOW PENTAGON, rightSocket=MAGENTA OCTAGON, data=----1------3--------1
id=86, plug=BLUE HEXAGON, leftSocket=YELLOW TRIANGLE, rightSocket=MAGENTA OCTAGON, data=----1------3---------
id=87, plug=BLUE OCTAGON, leftSocket=MAGENTA CIRCLE, rightSocket=RED SQUARE, data=---1------3-------2--
id=88, plug=MAGENTA PENTAGON, leftSocket=BLACK DIAMOND, rightSocket=YELLOW OCTAGON, data=-1------3------------
id=89, plug=BLUE OCTAGON, leftSocket=CYAN CIRCLE, rightSocket=CYAN TRIANGLE, data=-1------3------------
id=90, plug=GREEN TRIANGLE, leftSocket=MAGENTA CIRCLE, rightSocket=BLUE OCTAGON, data=----1------3--------1
id=91, plug=WHITE STAR, leftSocket=BLACK PENTAGON, rightSocket=WHITE STAR, data=-----1------3--------
id=92, plug=GREEN TRIANGLE, leftSocket=GREEN STAR, rightSocket=WHITE HEXAGON, data=-1-1----3-3-----3---1
id=93, plug=BLACK TRIANGLE, leftSocket=CYAN TRIANGLE, rightSocket=YELLOW SQUARE, data=-1-1----3-3-----3---1
id=94, plug=WHITE SQUARE, leftSocket=GREEN HEXAGON, rightSocket=RED STAR, data=----1------3---------
id=95, plug=RED HEXAGON, leftSocket=YELLOW HEXAGON, rightSocket=GREEN DIAMOND, data=---1------3-------2--
id=96, plug=WHITE SQUARE, leftSocket=CYAN PENTAGON, rightSocket=YELLOW OCTAGON, data=-----------------2---
id=97, plug=MAGENTA TRIANGLE, leftSocket=YELLOW CIRCLE, rightSocket=BLUE SQUARE, data=---1------3---------1
id=98, plug=MAGENTA SQUARE, leftSocket=CYAN OCTAGON, rightSocket=YELLOW DIAMOND, data=---1------3----------
id=99, plug=BLACK HEXAGON, leftSocket=YELLOW HEXAGON, rightSocket=BLUE TRIANGLE, data=-----------------2---
id=100, plug=MAGENTA TRIANGLE, leftSocket=YELLOW CIRCLE, rightSocket=WHITE HEXAGON, data=-1------3------------
id=101, plug=WHITE OCTAGON, leftSocket=CYAN TRIANGLE, rightSocket=CYAN CIRCLE, data=---1------3----------
id=102, plug=MAGENTA TRIANGLE, leftSocket=RED TRIANGLE, rightSocket=CYAN CIRCLE, data=---------------------
id=103, plug=GREEN STAR, leftSocket=WHITE OCTAGON, rightSocket=WHITE PENTAGON, data=----1------3--------1
id=104, plug=WHITE STAR, leftSocket=CYAN STAR, rightSocket=RED PENTAGON, data=-1------3------------
id=105, plug=CYAN DIAMOND, leftSocket=YELLOW TRIANGLE, rightSocket=YELLOW CIRCLE, data=---------------------
id=106, plug=WHITE SQUARE, leftSocket=CYAN PENTAGON, rightSocket=GREEN CIRCLE, data=---1------3--------1-
id=107, plug=YELLOW TRIANGLE, leftSocket=BLUE DIAMOND, rightSocket=GREEN SQUARE, data=---------------------
id=108, plug=WHITE DIAMOND, leftSocket=WHITE CIRCLE, rightSocket=RED STAR, data=-------1------3------
id=109, plug=YELLOW PENTAGON, leftSocket=BLACK CIRCLE, rightSocket=BLACK DIAMOND, data=-----1------3-------1
id=110, plug=BLUE DIAMOND, leftSocket=YELLOW CIRCLE, rightSocket=WHITE OCTAGON, data=----1------3-------1-
id=111, plug=RED STAR, leftSocket=YELLOW SQUARE, rightSocket=WHITE OCTAGON, data=-------------------3-
id=112, plug=WHITE DIAMOND, leftSocket=GREEN TRIANGLE, rightSocket=BLUE DIAMOND, data=-------1------3------
id=113, plug=RED SQUARE, leftSocket=GREEN HEXAGON, rightSocket=GREEN PENTAGON, data=----1-1----3-3------1
id=114, plug=YELLOW CIRCLE, leftSocket=GREEN PENTAGON, rightSocket=WHITE CIRCLE, data=----1------3------2--
id=115, plug=CYAN TRIANGLE, leftSocket=GREEN CIRCLE, rightSocket=YELLOW DIAMOND, data=-----1------3--------
id=116, plug=BLUE PENTAGON, leftSocket=BLUE HEXAGON, rightSocket=WHITE SQUARE, data=-----------------2---
id=117, plug=BLUE SQUARE, leftSocket=YELLOW PENTAGON, rightSocket=WHITE STAR, data=--1------3-----------
id=118, plug=YELLOW DIAMOND, leftSocket=BLUE PENTAGON, rightSocket=CYAN OCTAGON, data=----1------3---------
id=119, plug=WHITE HEXAGON, leftSocket=BLUE HEXAGON, rightSocket=GREEN TRIANGLE, data=--1------3-----------
id=120, plug=YELLOW TRIANGLE, leftSocket=BLUE DIAMOND, rightSocket=YELLOW SQUARE, data=--1-1----3-3----3---1
id=121, plug=WHITE OCTAGON, leftSocket=RED OCTAGON, rightSocket=WHITE SQUARE, data=----1------3-------1-
id=122, plug=MAGENTA PENTAGON, leftSocket=GREEN STAR, rightSocket=CYAN SQUARE, data=--1------3-----------
id=123, plug=BLACK SQUARE, leftSocket=RED PENTAGON, rightSocket=BLUE TRIANGLE, data=--1-1----3-3----3---1
id=124, plug=BLACK OCTAGON, leftSocket=BLUE DIAMOND, rightSocket=MAGENTA TRIANGLE, data=----1------3------2--
id=125, plug=CYAN STAR, leftSocket=MAGENTA STAR, rightSocket=CYAN TRIANGLE, data=-----1------3--------
id=126, plug=WHITE DIAMOND, leftSocket=YELLOW TRIANGLE, rightSocket=MAGENTA OCTAGON, data=-----1------3-------1
id=127, plug=BLACK SQUARE, leftSocket=BLACK TRIANGLE, rightSocket=BLUE CIRCLE, data=-----1------3--------
id=128, plug=BLUE CIRCLE, leftSocket=WHITE CIRCLE, rightSocket=BLUE TRIANGLE, data=-----------------2---
id=129, plug=GREEN TRIANGLE, leftSocket=CYAN CIRCLE, rightSocket=YELLOW PENTAGON, data=--1------3-----------
id=130, plug=BLUE PENTAGON, leftSocket=CYAN STAR, rightSocket=RED STAR, data=----1------3---------
id=131, plug=BLACK DIAMOND, leftSocket=WHITE DIAMOND, rightSocket=GREEN STAR, data=-----1------3-------1`