let input3 = `*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.
..*...*.*.*.....*.*.*.*.*.*...*.*...*.*
.*.*.*...*.*...*.*...*.*.....*...*.*...
..*.*...*.*...*...*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*...*.*.*.
*.*.*.*...*.*.*.*...*...*...*.*.*...*.*
.*...*.*.*.*.*.....*...*.*.*.*.*.*.*...
*.*.*...*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*
...*...*.*.....*.*.*.*...*...*.*.*...*.
*.*.*...*.*.*.*.*...*.*...*.*.*.*.*.*..
...*.*...*.*.*.*.*.*.*.*.*.*.*.*.*...*.
*.*.*.*.*...*...*.*.*...*.*.*.*.*.*.*.*
.*.*.*.*.*...*.*.*...*.*.*.*.*.*...*.*.
*.*.*.*.*.*...*.*.*...*.*.*.*.*.....*.*
.*.....*.*.*.*.*.*.*.*.*.*.*...*.*.*...
..*.*.*.*.*.*.*.*...*.*...*...*.*...*.*
.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.
*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.

RRLLRLRRRRRLLRRRLLRL
RRRLRRLLRRRRLRRRRLRL
LRRRLLLLLRLLLLLLRLLL
LRRLRRRLRRLRRLRRLRRR
LLRRRLRRRLLRLRRLLRLR
LLLLLLLLLRLLLLLRLRLL`

let inputt3 = `*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.
..*.*.*.*.*.*.........*.*.*.*.....*.*.*
.*.*...*.*.*.*.*.*.*.*.*.*.*...*.*.*.*.
*.*.*.*...*.*.*.*.*.....*.*.*.*...*.*..
.*...*.*...*.*.*.*.*.*.*.....*.*.*.*.*.
*.*.*.*.*.....*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*...*.*.*.*.....*.*.*.*...*.
*.*...*.*.*.*.*.*.*.*...*.*.*...*.*.*.*
.*...*.*.*.*.*.*.*.*...*.*.*.*.*.*.*.*.
*.*.*.*.*.*...*.....*.*...*...*.*.*.*.*
.*...*.*.*.*.*...*.*.*.*.*...*.*...*.*.
*.*.*.*.*...*.*.*.*.*.*.*.*...*.*.*.*.*
.*.*.*.*.*.*.*.*...*.*.*.*.*.*.*.*.*.*.
....*.*.*.*...*.*.*.*.*.*.*...*.*.*...*
.*.*.*...*.*.*.*.*...*.*.*.*.*.*.*.*...
*.*.*.*.*.*.*.....*...*...*.*.*.*.*.*.*
.*.*...*.....*.*.*.*.*.*.*...*.*.*.*.*.
*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.

RRRRLLRRLLLLLLLRLLRL
RRRRRRRLRRLRRLRRRLRR
RRRLLRRRRRLRRRRRLRRR
LLLLRRLLRRLLLLLRRLLL
LRRRRLRRLRLLRLLRRLRR
RRRRRRRRLRRRRLLRRRLR`

let input2 = `*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.
*.*.*...*.*.*.*.*.*...*.*
.*.*...*.*.*.*.*.*.*...*.
*...*.*.*.*.*.*.*.*...*.*
.*.*.*...*.*.*...*.*.*.*.
*...*...*.*.*.*...*.*.*.*
.*.*...*.*.*.*.*.*.*.*.*.
*.*.*...*.*.*.*.*.*.*.*.*
.*...*.*.*.*.*.*.*.*.*.*.
*.*.*.*.*.*...*.*.*.*...*
.*.*.*...*.*...*.*...*.*.
*.*...*.....*.*.*.*.*.*..
...*.*.*.*.*.*.*...*.*.*.
*.*.*.*...*.*.*.*.*.*.*.*
...*.*...*.*.*.*.*.*.*.*.
*.*.....*...*.*.*.*.*.*..
.*.*.*...*.*.*.*.*.*.*.*.
*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.

LRLRRLLRRRRLRRRLRRRR
LLRRRRRRRRRRRRRLRRRR
LLLRLRLLRLLLLLRLLLRL
RLRLRRLRLRRRLLLRRLLR
RRRRRRRRRRRRLRRRRRRR
LLLLRLLLLLLLRLRLLLRL
LLRLLLLRLLLLRRLLRLRL
RLRLLRRLRRRRRLRRRRRR
LLLLLLRLLLLLLLLRLRLL
LLRLRRLRRLRLRRLLLLLL
RRRRRRRRRRRRLRRRLLRR
LRLLRLRLLRRLLLLLLLLL
LRRLLLLRRLLRRRRRLRRL
RLRRLLRRLRRLRRLRRRRR
RLLLLLRLLLLRLRLLRLLL
RRRRLRRRLRRRRRRLRLLR
RRRRRRRRRLLRRRRRLRLR
LRLLLLLLRLLLLLRLLRRL
RRLLRLRRRLLLLLLLLRLR
LRLRRLRRRRRRRRRLLRLR
RLLLLLLLRLLRLLLLLLLL
RRRRLRRRLLLLLRLRRRLL
LRRRLRRRRRLRRRRRRRRR
LLRLRLLLLLLLLRLLLLLL
LLRLLLLRLRRRLRRLLLLL
RRRRRRRRRRRRRRLRRRRR
LRLRLLLRLLLRLRLLLLLR
RRLRRLLLLRRLRLLRLRRL
RRRRRRRRRRRLLRRRRRRL
LLLLRLLRLLLRLLRLLLRL
RLRRLRRRRRLLLLLLRRLR
RRRRRRLLRRRRRRRLRRRR
LLRRLLLLRLRLLLRLLRLL
RRRLRLLRLRLLLLRRLRLR
RLLRRRRRRRRRRLRRRRRR
RLLRRLLLRLRLLRLLLLLL
RLLRRLLLRRRRRLRRLLLL
RRRRRLRLRRRRRRRLRRRR
LLRLLRLLLLLLLLRLLLRL
RLRRRRRRRRLRLRLRLRLR
RRRRRRRRLLRRRLRRRRRR
LLLRLLLLLLLRLLRLRRRL
RLLRRLRLLLLRLRLRRRLL
RRRRRLRRRRRLLRRLRLRR
LLLLLLLLLRLLRLLRLLLL
RLRRRLRLLRLRLLRRRLRR
RRLRRLRRRRRRRRLLRRRL
RLRLLLLRLLLRLLLLLRLL
LLRLRRLLLLRLLRLLLLRL
RRRLRRRRRRRRLLRLRRRR
RLRLLRLLLLLLLLRRLLRL
RLLRLLLLRLRRRLRRRLLL
RLRRRRRRRRLRLRLLRRRR
LLLLLLLLLLLLLLLLLLLL
RLLRRRLLRLRRLRRRLRLR
RLRRLRRRLLLLRRRRRRRL
LLLRRLLLLRLLLLLRLLLR
RRLLLLLLRLLRLLRLRLRL
RRRRRRLRLRRRRRRLRRRR
RRLLLLLLLLRLLLLLLLLR
RRLLLLLLRRLRRRRRRLLR
LRRRRRLRRRRRRRRLRRRR
LLLLLLLLRRLLRLLLRLLL
LLRLRLRRLRRRRLRRLRRL
RRRRLRRRRLRRRRLRRLLR
RLRLRRLRLRLLLLLLLLLL
LRRRLRRLRLRRRLLRLLLL
RRRRRRRRRLRRRRRRRRRR
LLLLLLLLLLLRLRLRLRLL
LRLLLLLLRLLRRLRRRLLL
RRRRRRRRRRRRRRRLLLRR
LLRLRLRLLRLLLLLLLRLL
RRRLLRLLLRRRLLLRLRRR
RRLRRRRRRRRRRRRLRRRR
LLLLLRLLLLLLLLLLLLLL
LLRLRRRLRRLLLLLLRLLR
RRRLRRRRRRRRLLRRRRRL
LLLLLLRLLRLLLLLRLLLL
RRRRLLLLRRRLLLLLRRLL
LRLLRRRRRLRRRLRLRRRR
LLLLLLLLLLLLLLLLLLLR
LLRRRLLRRRRRRLLRLLRR
RLRRLRLRRRRRRRRLLRRR
LLLLLRLLLLLLLLLRLLLL
LRLLLRLLLRLLLRLRLLLL
RRRLRRRRRRRRRRRRLRRR
LLRLRLLLLLLRLLLLLLRL
LLRRLLLRLRLLLRLRRRLR
RRRRRLLRRRRLRLRRRLRR
LLLLLLLLLLRLLLRLLLLR
RRLLLRRLRLRLLRLLRLLR
RRRRRRRRRRRLRRRLRRRR
LRRLRLLRLLLLLLLLLLLL
LLRRRLRLLRLLRRRRLRRR
RRRRRRRRRRRRLRRRRRRR
RLLRLLLLLRLRLLLLLLLL
LLLRLRLRRLLLRLRLRLRL
RLLLRRRRRRRRRRRLRLRR
LLLLLLLLLLLLLLLLLLLL
RRRRRRRRRRRRRRRRRRRR`

let inputt2 = `*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.
..*.*.*.*...*.*...*.*.*..
.*...*.*.*.*.*.*.....*.*.
*.*...*.*.*.*.*.*...*.*.*
.*.*.*.*.*.*.*.*.......*.
*.*.*.*.*.*.*.*.*.*...*..
.*.*.*.*.*.*.*.*.....*.*.
*.*...*.*.*.*.*.*.*.*....
.*.*.*.*.*.*.*.*.*.*.*.*.
*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*...*.*.
*.*.*.*.*.*.*.*.*...*.*.*
.*.*.*.*.*.*.*.*.....*.*.
*.*.*.*.*.*.*.*...*...*.*
.*.*.*.*.*.*.*.*.*.*.*.*.
*.*.*...*.*.*.*.*.*.*.*.*
.*...*.*.*.*...*.*.*...*.
*.*.*.*.*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.*.*.*.*.

RRRLLRRRLLRLRRLLLRLR
RRRRRRRRRRLRRRRRLLRR
LLLLLLLLRLRRLLRRLRLL
RRRLLRRRLLRLLRLLLRRL
RLRLLLRRLRRRLRRLRRRL
LLLLLLLLRLLRRLLRLLLL
LRLLRRLRLLLLLLLRLRRL
LRLLRRLLLRRRRRLRRLRR
LRLLRRLRLLRLRRLLLRLL
RLLRRRRLRLRLRLRLLRRL`

let input1 = `*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.
*.*.*.......*.*.*
...*.*.*.*.*.*.*.
*.*.*...*...*.*.*
.*.*.*.*.*.*.*.*.
*.*.*.*.*.*.*...*
.*.*.*...*.*...*.
*.*...*.*.*...*.*
.*.*.*...*.*.*.*.
*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.

LRLRRLLLRLRL
LRLLRRRLRLRR
RRRLLRLRLLRL
RLRRRLRRRLLR
RRRRRLRLRRRR
LLLLLRLLLLRR
LLRRLLRLRRLL
RLRRRRRRRRRL
RLRLRRLLLLRL`;

let inputt = `*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.
*.*.*...*.*...*..
.*.*.*.*.*...*.*.
*.*.....*...*.*.*
.*.*.*.*.*.*.*.*.
*...*...*.*.*.*.*
.*.*.*.*.*.*.*.*.
*.*.*...*.*.*.*.*
.*...*...*.*.*.*.
*.*.*.*.*.*.*.*.*
.*.*.*.*.*.*.*.*.

RRRLRLRRRRRL
LLLLRLRRRRRR
RLLLLLRLRLRL
LRLLLRRRLRLR
LLRLLRLLLRRL
LRLRLLLRRRRL
LRLLLLLLRLLL
RRLLLRLLRLRR
RLLLLLRLLLRL`